export const GET_CATEGORIES = 'GET_CATEGORIES' 
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS' 
export const GET_CATEGORIES_FAILED = 'GET_CATEGORIES_FAILED'
export const SET_EXTRA_PROP = 'SET_EXTRA_PROP'